apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-sp
  template:
    metadata:
      labels:
        app: my-sp
    spec:
      containers:
      - name: my-image
        image: spchuah1/intel1:latest
        ports:
        - containerPort: 8080
